export const REGISTER_USER = 'REGISTER_USER'
export const GET_USERS = 'GET_USERS'
export const LOGIN = 'LOGIN'
export const FILTER = 'FILTER'
export const GET_POKEMONS = 'GET POKEMONS'
export const CREATE_POKEMON = 'CREATE_POKEMON'
export const UPDATE_POKEMON = 'UPDATE_POKEMON'
export const ADD_POKEMON = 'ADD_POKEMON'
export const REMOVE_POKEMON = 'REMOVE_POKEMON'
export const GET_TYPES = 'GET_TYPES'
export const UPDATE_POKEMONS_TEAM = 'UPDATE_POKEMONS_TEAM'


